Feature/project structure
BottleRocketStudios/iOS-Hyperspace pull request #151
Opened 2022-01-13 19:31 UTC by wmcginty

Restructured the project to make it easier to edit, opening the workspace allows you to edit the module and its example in a "real" scenario. Also moves the documentation and deployment information into the workspace for easier editing.

<img width="294" alt="Screen Shot 2022-01-14 at 5 18 13 PM" src="https://user-images.githubusercontent.com/7141301/149597347-6aae33fc-85c3-46f0-b6cd-d3c1b1fcff46.png">

2022-01-25 20:27 UTC, br-tyler-milner submitted a review, later dismissed

2022-01-26 20:21 UTC, br-earl-gaspard requested changes

2022-01-26 20:21 UTC, br-earl-gaspard commented on Sources/Core/Service/Transport/TransportSession.swift
> +////  Copyright © 2017 Bottle Rocket Studios. All rights reserved.
Too many forward slashes here.

2022-01-26 20:27 UTC, br-earl-gaspard requested changes

2022-01-26 20:27 UTC, br-earl-gaspard commented on Sources/Core/Service/Transport/TransportSession.swift
> +
This blank line should have 2 slashes.

2022-01-26 20:29 UTC, br-earl-gaspard approved these changes

2022-01-26 20:35 UTC, br-earl-gaspard approved these changes

2022-01-26 20:36 UTC, br-tyler-milner approved these changes

2022-01-26 21:16 UTC, merged